### PR TITLE
Allow retrieving students from section

### PR DESCRIPTION
**Pull request by bgarciaentornos**
Also adding missing enrollment type

### CODE REVIEW

**Comment by bgarciaentornos** [comment]
Integration tests too?

**Comment by buckett** [comment]
I'm not too fussed about integration tests for this, just a small example of the JSON and it being successfully parsed.

**Comment by mpellicer** [comment]
This is paired with:
https://github.com/oxctl/course-management/pull/70

**Comment by bgarciaentornos** [comment]
Added JSON parsing tests.

**Comment by buckett** [comment]
This should be in 1.4.6

**Pull request merged**
