### PR TITLE
Retrieve user Profile

### PR DESCRIPTION
**Pull request by bgarciaentornos**
https://canvas.instructure.com/doc/api/users.html

This is basically for retrieving the user timezone. I think this is the best way to go through this considering the current status of the
library: User and Profile share 95% of the fields and this User model already has bio or timezone.

I'd like to know your opinion on this matter though.

Thanks and regards.

### CODE REVIEW

**Comment by buckett** [comment]
I can see this is a quick fix, but one of the benefits of the library is that the Java classes add some type safety and are self documenting. Returning a User and have the caller remember that this is a profile and some fields will not be set doesn't seem like a good solution.

**Comment by bgarciaentornos** [comment]
I surely agree with that but I guess the original problem comes from Canvas documentation, which is a bit messy and doesn't split both objects totally. Besides sharing fields, if you take a look at the API the bio and timezone are supposed to appear on the User class (and in fact I think you might set them on creation) but they are only retrieved with the get Profile url.

I'm not sure if all this was considered when the User class was initially added, but at this point forcing separated objects and methods would break backwards compatibility and add redundancy.

But having said that, if you still believe separation is the way to go, then I'll work on that. No problem.

**Comment by bgarciaentornos** [comment]
Little update: pronouns are nowhere to be found on the classes description, but they can be updated using the edit user endpoint and read using both the profile and the user one (unlike bio or timezone which are profile only).

I considered adding a new class for all the shared fields but I think I am going to add a separated profile class with a read only endpoint so we can have it in there. I don't feel like touching the User class much at this point.

**Comment by bgarciaentornos** [comment]
Hi @buckett 

Back in July I created another PR following the approach you had proposed: https://github.com/oxctl/canvas-api/pull/57

Regards.

**Comment by mpellicer** [comment]
Shall we close this PR and merge #57 instead?

**Pull request closed without merging**
