### PR TITLE
CM-322 - Add support for Course Audit Log objects

### PR DESCRIPTION
**Pull request by mpellicer**

### CODE REVIEW

**Comment by buckett** [comment]
Nice, but I don't see how it will process the pagination on the audit events, if there are multiple pages of events won't it just retrieve the first?

**Comment by mpellicer** [comment]
> Nice, but I don't see how it will process the pagination on the audit events, if there are multiple pages of events won't it just retrieve the first?

You're right, I tested with a course with more than 10 events and the object only returns the first 10 events, damn.

**Comment by mpellicer** [comment]
Have you seen something like this?
image

Instead of requesting a specific page Canvas is requesting a bookmark.

**Comment by buckett** [comment]
Yeah I think enrollments API has something similar. I'd guess they are using something like named cursors to reduce the performance hit of asking for the second and third pages of a query: https://www.postgresql.org/docs/9.2/plpgsql-cursors.html

**Comment by mpellicer** [comment]
Well, I've added support to multiple pages that return single objects.

I'm not sure if we're going to use this endpoint in our C/U/D development items, at least I'm not going to use it in our reports.

**Comment by mpellicer** [comment]
I think we don't need this anymore, makes sense to close it.

**Comment by buckett** [comment]
Closing this as we don't need it.

**Pull request closed without merging**
